app_homepage:
    path:       /
    defaults:   { _controller: AppBundle:Default:index }

app_posts:
    path:       /post
    defaults:   { _controller: AppBundle:Post:index }

app_post_view:
    path:       /post/{id}
    defaults:   { _controller: AppBundle:Post:view }
