<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimePassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimePassRepository extends EntityRepository
{
    /**
     * @param \AppBundle\Entity\Post $post
     * @return array
     */
    public function findByPost(Post $post)
    {
        $query = $this->createQueryBuilder('tp');

        $query
            ->where('tp.category IS NULL OR tp.category = :category')
            ->setParameter('category', $post->getCategory())
            ->addOrderBy('tp.category', 'desc')
            ->addOrderBy('tp.price', 'asc')
        ;

        return $query->getQuery()->getResult();
    }

}
